import Foundation

/// Search Preview 用サンプルデータ
enum SearchPreviewData {

    static let document: SearchDocument = SearchDocument(
        items: items,
        entityName: "Article",
        searchFieldNames: ["title", "body"],
        allFieldNames: ["id", "title", "body", "category", "status", "author"]
    )

    static let items: [SearchableItem] = [
        SearchableItem(
            id: "doc-001",
            textFields: [
                "title": "Introduction to Machine Learning",
                "body": "Machine learning is a subset of artificial intelligence that focuses on building systems that learn from data. Deep learning uses neural networks with many layers."
            ],
            allFields: ["id": "doc-001", "category": "Technology", "status": "published", "author": "Alice"]
        ),
        SearchableItem(
            id: "doc-002",
            textFields: [
                "title": "Natural Language Processing Basics",
                "body": "NLP combines computational linguistics with machine learning to enable computers to process and understand human language. Tokenization and parsing are fundamental steps."
            ],
            allFields: ["id": "doc-002", "category": "Technology", "status": "published", "author": "Bob"]
        ),
        SearchableItem(
            id: "doc-003",
            textFields: [
                "title": "Database Design Patterns",
                "body": "Effective database design requires understanding normalization, indexing strategies, and query optimization. FoundationDB provides ACID transactions at scale."
            ],
            allFields: ["id": "doc-003", "category": "Technology", "status": "published", "author": "Carol"]
        ),
        SearchableItem(
            id: "doc-004",
            textFields: [
                "title": "The Art of Japanese Gardens",
                "body": "Japanese gardens reflect deep philosophical traditions including wabi-sabi and zen aesthetics. Stone arrangements and water features create contemplative spaces."
            ],
            allFields: ["id": "doc-004", "category": "Art", "status": "published", "author": "Diana"]
        ),
        SearchableItem(
            id: "doc-005",
            textFields: [
                "title": "Quantum Computing Fundamentals",
                "body": "Quantum computers use qubits that can exist in superposition states. This enables parallel computation for certain problems like factoring and optimization."
            ],
            allFields: ["id": "doc-005", "category": "Science", "status": "draft", "author": "Eve"]
        ),
        SearchableItem(
            id: "doc-006",
            textFields: [
                "title": "Swift Concurrency Deep Dive",
                "body": "Swift concurrency introduces async/await, actors, and structured concurrency. These features enable safe concurrent programming without data races."
            ],
            allFields: ["id": "doc-006", "category": "Technology", "status": "published", "author": "Alice"]
        ),
        SearchableItem(
            id: "doc-007",
            textFields: [
                "title": "Understanding Graph Databases",
                "body": "Graph databases excel at modeling relationships. They use nodes and edges to represent connected data, enabling efficient traversal queries like shortest path."
            ],
            allFields: ["id": "doc-007", "category": "Technology", "status": "published", "author": "Bob"]
        ),
        SearchableItem(
            id: "doc-008",
            textFields: [
                "title": "Modern Architecture Trends",
                "body": "Sustainable architecture incorporates green materials and energy-efficient design. Biophilic design brings natural elements into built environments."
            ],
            allFields: ["id": "doc-008", "category": "Art", "status": "published", "author": "Carol"]
        ),
        SearchableItem(
            id: "doc-009",
            textFields: [
                "title": "Vector Search and Embeddings",
                "body": "Vector search enables semantic similarity matching using embeddings generated by neural networks. HNSW and IVF are popular approximate nearest neighbor algorithms."
            ],
            allFields: ["id": "doc-009", "category": "Technology", "status": "draft", "author": "Diana"]
        ),
        SearchableItem(
            id: "doc-010",
            textFields: [
                "title": "Climate Science Overview",
                "body": "Climate models simulate Earth systems to predict future conditions. Machine learning helps improve prediction accuracy for extreme weather events."
            ],
            allFields: ["id": "doc-010", "category": "Science", "status": "published", "author": "Eve"]
        ),
    ]
}
